<?php
//Ids

/**
 * Provides the module content type.
 * @file
 */

/**
 * Implements hook_perm()
 */
function beats_perm() {
  return array('administer 3beats', 'access 3beats');
}



/**
 * Implementation of hook_menu
 */
function beats_menu()
{
	$items = array();
	$items['home'] = array(
			'title' => '3beats Live Updates',
			'description' => t('3beats Live Updates'),
			'page callback' => 'get_live_updates',
        		'access arguments' => array('access 3beats'),
			'type' => MENU_NORMAL_ITEM,
        );
	
	$items['celebrities'] = array(
			'title' => 'Celebrities',
			'description' => t('Celebrities'),
			'page callback' => 'get_celebrities_profile',
        		'access arguments' => array('access 3beats'),
			'type' => MENU_NORMAL_ITEM,
        );

	$items['home'] = array(
		'title' => 'keyword form',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('test_page'),
		'access arguments' => array('access 3beats'),
		'type' => MENU_NORMAL_ITEM,
		);

	$items['my/result'] = array(
		'title' => 'Result Page',
		'page callback' => 'search_result',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
		);

	return $items;
}

/**
 * Show options to select subscription type
 */
function get_live_updates()
{

$sql_latest_comment=db_query("select comments.name,comments.subject,comments.comment,node.nid,node.title,node.uid ,node.type  from comments 
				inner join node on comments.nid=node.nid
				where node.type='celebrities'
				order by cid desc limit 0,6");
while($result=db_fetch_object($sql_latest_comment))
{
	$celeb_pic=node_load($result->nid);
	$output.=' <div>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-left:-2px;">
                    <tr>
                      <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td valign="top" class="homeSpecs_purplebox"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                              <td class="homeSpecs_headings" style="padding-left:20px">'.$result->title.'<span>(3429 comments)</span></td>
                            </tr>
                            <tr>
                              <td align="left" class="homeSpecs_headings"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                  <td align="center" class="homeSpecs_purplebox_left" style="padding-top:15px"><a href="'.base_path()."celebrities/".$result->nid.'"><img src="'.base_path().$celeb_pic->field_celeb_pic['0']['filepath'].'" width="50" height="50" /></td>
                                  <td valign="top"><table width="100%" border="0" cellspacing="15" cellpadding="0">
                                    <tr>
                                      <td width="6%" height="50">'.user_picture($result->uid).'</td>
                                      <td width="94%" class="homeSpecs_grid_content"><span>'.$result->name.' :</span> &nbsp; <img src="'.base_path().'sites/all/themes/3beats/images/thumb.gif" width="17" height="23" /><span class="homeSpecs_thumb">+7</span> '.$result->comment.'(<br />
                                      <a href="#">'.$result->subject.'<span> </span></a></td>
                                    </tr>
                                  </table></td>
                                </tr>
                              </table></td>
                            </tr>
                          </table></td>
                        </tr>
                      </table></td>
                    </tr>
                    
                    
               

                   
                    
                    <tr>
                      <td>&nbsp;</td>
                    </tr>
                  </table>
                </div>';
}

	return $output;

}



function get_celebrities_profile()
{
	$output='<div class="newline"></div>
                
                
                <div>
                	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="50%">
		'.celebrities_bio().'
    </td>
    <td width="50%" align="left" valign="top" style="padding-left:20px;"><h3 class="subheading">Crowd  Pulse on Lilly Allen  <span>4m | 1m | 2wk | 2d | 1h</span></h3><img src="'.base_path().'sites/all/themes/3beats/images/graph.gif" width="429" height="223" /></td>
  </tr>
</table>

                
                </div>
                <div style="border:0px solid #CCC; margin-top:20px;">
              
                	<div style="width:560px;  float:left ">
                      <h2 class="subheading">Comment Stream </h2>


                	 '.comment_show_celebrities().'
                	  
              	        

		     



              	    </table>
                   
                    </div>
                   '.latest_on_lilly().'
                
                </div>
                <div style="clear:both"></div>';

	return $output;
}

function latest_on_lilly()
{

$arg=arg(1);
$sql = db_fetch_object(db_query("select * from node where nid='$arg'"));
$node_result = node_load($sql->nid);
//echo "<pre>";
//print_r($node_result->field_latest_celeb_news['0']['value']);
$output=' <div style="width:320px; float:left; margin-left:20px; padding-left:20px; border-left:1px dashed #bbb104"> <h2 class="subheading">Latest on '.$node_result->title.'</h2>
                    <p>'.$node_result->field_latest_celeb_news['0']['value'].',<br />
                      <br />
                    </p>
                   

                   <div style="border-top:1px dashed #bbb104">
                    
                    <p>

                    <h3 class="subheading"><br />
                     What is your Pulse on Lilly ?</h3>
                    <img src="'.base_path().'sites/all/themes/3beats/images/pulse.gif" width="305" height="53" /><br />
                    <div class="comment_bg">
                    	<textarea name="" cols="" rows="" style="background-color:transparent; width:260px; overflow:hidden;"></textarea>
                   	  <br />
<br />

                    </div>
                    <div style="text-align:right; padding-right:20px;">
                    
                    	<img src="'.base_path().'sites/all/themes/3beats/images/cancel_btn.gif" />&nbsp;<img src="'.base_path().'sites/all/themes/3beats/images/submit_btn.gif" /><br />
<br />

                    </div>
                   </div>

                   <div style="border-top:1px dashed #bbb104;border-bottom:1px dashed #bbb104"><br />
                                       
                   '.more_celeb_links().'
                    
                    </div><br />

                     '.similar_celebrities().'
                    
                    
                  </div>
                    
                    ';	

		    return $output;
}

function celebrities_bio()
{
	$arg=arg(1);
	$sql = db_fetch_object(db_query("select * from node where nid='$arg'"));
	$node_result = node_load($sql->nid);
	//echo "<pre>";
	//print_r($node_result->field_celeb_pic['0']['filepath']);
	//print_r($node_result->body);
	$output='<div style="width:450px; padding-left:20px;">
			<img src="'.base_path().$node_result->field_celeb_pic['0']['filepath'].'" width="189" height="245" style="float:left; padding-right:20px" />
			<span style="color:#ffffff;">'.$node_result->body.'</span>
		</div><div><a href="'.base_path().'comment/reply/'.$arg.'#comment-form">Add Comments</a></div>';
		return $output;
}

function comment_show_celebrities()
{
global $user;
$user->picture;
 $arg=arg(1);
 $sql_comment=db_query("select * from comments where nid='$arg' order by cid desc");
 while($result = db_fetch_object($sql_comment))
 $output.=' <table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-left:-2px;">
                	    <tr>
                	      <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                	        <tr>
                	          <td valign="top" class="grid_bg"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                	            <tr>
                	              <td align="left" class="homeSpecs_headings"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                	                <tr>
                	                  <td valign="top"><table width="100%" border="0" cellspacing="15" cellpadding="0">
                	                    <tr>
                	                      <td width="6%" height="50">'.user_picture($result->uid).'</td>
                	                      <td width="94%" class="homeSpecs_grid_content"><span>'.$result->name.' :</span> &nbsp;
						 <img src="'.base_path().'sites/all/themes/3beats/images/thumb.gif" width="17" height="23" /><span class="homeSpecs_thumb">+7</span> 
						'.$result->comment.':(<br />
                	                        <a href="#">'.$result->subject.' <span> </span></a></td>
              	                      </tr>
              	                    </table></td>
              	                  </tr>
              	                </table></td>
              	              </tr>

              	            </table></td>
              	          </tr>
              	        </table></td>
              	      </tr>
		
		      
		      ';

 return $output;
}

function user_picture($uid='')
{

$sql=db_fetch_object(db_query("select picture from users where uid='$uid'"));
$result = '<img src="'.base_path().$sql->picture.'" width="50" height="50" />';
return $result;
}

function get_node_title()
{
  $arg = arg(1);
  $sql=db_fetch_object(db_query("select title from node where nid='$arg'"));
  return $sql_>title;
}

function more_celeb_links()
{
$arg=arg(1);
$sql = db_fetch_object(db_query("select * from node where nid='$arg'"));
$node_result = node_load($sql->nid);
//echo "<pre>";
//print_r($node_result->field_more_links);
$output='<h3 class="subheading">More About '.$node_result->title.'
					</h3>
                    <div class="makemore">
                      <p>                      
                      <ul>';
	      foreach($node_result->field_more_links as $key=>$value){
			$output.='<li><a href="'.$node_result->field_more_links[$key]['url'].'">'.$node_result->field_more_links[$key]['title'].'</a></li>';
              }     
              $output.='<br/><br/></ul>
                    </p>
                    </div>';
		  
return $output;

}



function test_page()
{
	$form['name'] = array('#type' => 'textfield',
      '#title' => t(''),
      '#maxlength' => 255,
      '#default_value' => 'Enter the keywords',
      '#autocomplete_path' =>'search/keyword-autocomplete',
      '#required' => FALSE,
      '#prefix' =>'<div style="border:0px solid #ff0000;width:200px;">',
      '#suffix' =>'</div>',
      '#attributes' => array(
        'onclick' => 'this.value=""','style' =>'margin-top:-10px;'),
      );
    $form['submit'] = array('#type' => 'submit',
      '#value' => t(''),
      '#prefix' =>'<div style="border:0px solid #ff0000;width:80px;float:right;margin-top:-40px;">',
      '#suffix' =>'</div>'
    );
	return $form;
}

function test_page_submit($form, &$form_state)
{
  //echo "krishna is good boy";
  //echo "<pre>";
  //print_r($form_state['values']['name']);
  $form_state['redirect'] = 'my/result/'.$form_state['values']['name'].'';
}

function search_result()
{

  $arg = arg(2);
  $sql=db_query("select nid,title from node where title like '%%$arg%%' and type='celebrities'");

$output='';
while($result=db_fetch_object($sql))
	{
		$output.='<div><a href="'.base_path().'celebrities/'.$result->nid.'">'.$result->title.'</a></div>';
	}
return $output;
}


function similar_celebrities()
{
$arg=arg(1);
$termId = db_fetch_object(db_query("select tid from term_node where nid='$arg'"));

$nodeDetails = db_query("select node.nid,node.title,term_node.tid from node inner join term_node 
			 on node.nid=term_node.nid 
			 where term_node.tid='$termId->tid' and node.nid!='$arg'");

//echo "<pre>";
//print_r($node_result);
	$output='';
	$output.='<div class="similar_celebrities"><h3 class="subheading">Similar Celebrities</h3>
                     <ul>';
		     while($celebName = db_fetch_object($nodeDetails))
		     {
                       $output.='<li><a href="'.base_path().'celebrities/'.$celebName->nid.'">'.$celebName->title.'</a></li>';
		     }
		       
	$output.='</ul>
                     </div>';

        return $output;
}
